# Site settings
title: John Doe
description: "Software Developer & Finance Enthusiast"
url: "https://yourusername.github.io" # Your GitHub Pages URL
baseurl: "" # Leave this empty unless you are using a subfolder

# Author information
author:
  name: John Doe
  email: john.doe@example.com
  github: https://github.com/johndoe
  linkedin: https://linkedin.com/in/johndoe
  twitter: https://twitter.com/johndoe

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll

# Navigation links
navigation:
  - title: Home
    url: /
  - title: Resume
    url: /resume/
  - title: Projects
    url: /projects/
  - title: Contact
    url: /contact/

# Social links
social:
  - icon: twitter
    url: https://twitter.com/johndoe
  - icon: github
    url: https://github.com/johndoe
  - icon: linkedin
    url: https://linkedin.com/in/johndoe

# Google Analytics
google_analytics: UA-XXXXXXXXX # Replace with your track
